### ISSUE TITLE
Chapter 1: Open Source Community

### ISSUE THREAD

**Issue by Dimitry-bit** [Open-Source-Community/linux-handbook#1]
- [ ] Open Source Philosophy
  - [ ] Open Source Community Egypt

**Comment by AbdelrahmanKhatab9** [comment]
Hello Tony 👋

I am trying to push all the updates of CH 1 & 2, but I don't have the permission to push commits to solve the issues ... meanwhile we accept the invitation from habiba as a contributors in the repo :D ?
 
any way I am gonna FORK the repo, then making a pull request.

![Screenshot (2)](https://github.com/Open-Source-Community/linux-handbook/assets/99526626/86ae1141-3793-4324-a776-8f76e79e99d2)
